field: 8fea7832-8658-4760-82a2-fea191ae7ac0 # Blocks
fieldLayouts:
  c9f740fa-fe7c-4524-ba68-5db333bbc3e0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1782a7b8-9a4c-46f5-a0b7-2588b902cf4b # Sponsor title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b324bab8-3ac3-4b53-ba61-29b6ba2a3437
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9bc92fc0-6cd2-4b8e-b4b6-83eb6d181113 # Sponsor Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e0d6e6f-7d2d-4921-95a9-9ccd5d26fbaa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fdc3dce6-e5e4-41dc-a031-cbda756d5077 # Sponsor Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b46bf48-1765-45c0-9fd0-2827931ce58e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2f6722f7-e447-40db-b488-ab47620851dc
        userCondition: null
fields:
  9bc92fc0-6cd2-4b8e-b4b6-83eb6d181113: # Sponsor Logo
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: sponsorLogo
    instructions: null
    name: 'Sponsor Logo'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:3d5f9f28-5e41-424d-9e51-8c6791fe0561' # Public Assets
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:3d5f9f28-5e41-424d-9e51-8c6791fe0561' # Public Assets
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  1782a7b8-9a4c-46f5-a0b7-2588b902cf4b: # Sponsor title
    columnSuffix: ljtesozj
    contentColumnType: text
    fieldGroup: null
    handle: sponsorTitle
    instructions: null
    name: 'Sponsor title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fdc3dce6-e5e4-41dc-a031-cbda756d5077: # Sponsor Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: sponsorLink
    instructions: null
    name: 'Sponsor Link'
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: asset
      defaultText: ''
      enableAllLinkTypes: true
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
handle: sponsor
name: sponsor
sortOrder: 5
