baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'The Invisible Man Leadership Program'
primary: true
siteGroup: 16c32343-c234-4479-a53b-8de7cad7cf71 # The Invisible Man Leadership Program
sortOrder: 1
