columnSuffix: null
contentColumnType: string
fieldGroup: 7dd82277-b22c-4d92-993d-429ae8f92bf8 # Common
handle: blocks
instructions: null
name: Blocks
searchable: false
settings:
  contentTable: '{{%matrixcontent_blocks}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
