dateModified: 1676423171
email:
  fromEmail: me@levizitting.com
  fromName: 'The Invisible Man Leadership Program'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    7dd82277-b22c-4d92-993d-429ae8f92bf8: Common # Common
    16c32343-c234-4479-a53b-8de7cad7cf71: 'The Invisible Man Leadership Program' # The Invisible Man Leadership Program
plugins:
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'The Invisible Man Leadership Program'
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
