dateModified: 1681864362
dateModified: 1681864518
email:
  fromEmail: me@levizitting.com
  fromName: 'The Invisible Man Leadership Program'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  public:
    hasUrls: true
    name: Public
    settings:
      path: '@webroot/assets'
    type: craft\fs\Local
    url: '@web/assets'
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    0e32b2e3-7176-4e6b-b27a-a9d009520a89: Events # Events
    1f8ded3d-464f-4677-a20e-a7a8ace195b3: Image # Image
    3d5f9f28-5e41-424d-9e51-8c6791fe0561: 'Public Assets' # Public Assets
    3e6f485a-bd73-4877-a29e-329994951ea5: Cards # Cards
    4a8f835f-f041-427c-a837-acc1f3a8c973: Text # Text
    5ee7c67e-32cf-4b9c-b3fe-a14f86f2f60c: Header # Header
    6b6afd05-9cc6-4a8b-a9b0-426ae2ec21c5: 'Stats Table' # Stats Table
    7dd82277-b22c-4d92-993d-429ae8f92bf8: Common # Common
    8fea7832-8658-4760-82a2-fea191ae7ac0: Blocks # Blocks
    9bc92fc0-6cd2-4b8e-b4b6-83eb6d181113: 'Sponsor Logo' # Sponsor Logo
    16c32343-c234-4479-a53b-8de7cad7cf71: 'The Invisible Man Leadership Program' # The Invisible Man Leadership Program
    33b3fe32-761b-491c-bd8d-bbd1ee0e320a: Text # Text
    55fa79ea-5553-42d9-8e46-93726cd9c7e3: Heading # Heading
    67ed6635-8436-4a01-b83a-782899c82e34: foobar # foobar
    67ca25e8-eb03-43cd-9222-e8c0d90a1331: 'Public Schema' # Public Schema
    89c63208-2f9e-4fb3-9562-c5c4a709733f: Title # Title
    543ad2d6-6d93-4951-b825-32014289a267: sponsor # sponsor
    598a041c-a952-43d7-8130-a659fcddd233: 'Stat Group' # Stat Group
    645f9846-53fa-4e4d-9c85-4aa4f98574ae: 'Rich Text block' # Rich Text block
    665f6825-9a80-4138-a2bf-847c424ec67b: 'Stat Item' # Stat Item
    698fb72b-9d3b-499e-a0c9-63bb555150b8: Description # Description
    736cdbf1-41f2-49c9-9d94-9599ac7f26d3: Image # Image
    1467d9bb-2f87-4770-aa6e-91b0edc0353b: 'The Invisible Man Leadership Program' # The Invisible Man Leadership Program
    1782a7b8-9a4c-46f5-a0b7-2588b902cf4b: 'Sponsor title' # Sponsor title
    3686e5d4-d982-4c5e-a623-fe9f1ec6aba8: Text # Text
    4315b9f4-bbde-4b68-8395-340ea7f8203d: Stats # Stats
    5335c937-f52e-46bc-b450-ce1c783b5042: Title # Title
    7593fe81-7596-4faa-bef4-aac9d25d34e2: Hero # Hero
    59727c02-1fb5-44ba-97e1-7750af27abd4: 'Card Set' # Card Set
    a346e097-745f-4395-a326-411a4ff70c9d: 'Callout Link' # Callout Link
    b7cfb2f9-efc2-4e6f-b8a8-3d28d9d92e2f: Home # Home
    b54fd2e5-a591-4b7e-b183-a34f283cc000: Heading # Heading
    c9ad660a-b24e-4c3d-b87f-685185cc32f2: 'Background Image' # Background Image
    d5a81be2-83ca-46a2-a9d4-d97d68b8da6f: Home # Home
    e0a28370-0059-4791-9624-2383f68b6460: Heading # Heading
    e4c794ce-2250-48f7-86fe-cc451727b17f: 'Rich Text' # Rich Text
    e4f4af5c-69d6-4acc-9fc4-c70666b6c415: Simple # Simple
    ea4cc075-2720-4b5e-8764-d87555c1ba68: Heading # Heading
    f31fd87e-6a49-4079-ab58-f771fec5bb84: Timeline # Timeline
    f848d360-bf9c-4006-a125-b2fc0d8f0d90: Stat # Stat
    f2206ae6-9a42-4b03-b6fd-c88253dff38c: 'Example Input' # Example Input
    f9911ada-d8f1-439c-a699-315a06fc42f8: 'Sub Heading' # Sub Heading
    fdc3dce6-e5e4-41dc-a031-cbda756d5077: 'Sponsor Link' # Sponsor Link
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'The Invisible Man Leadership Program'
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
