dateModified: 1679444402
email:
  fromEmail: me@levizitting.com
  fromName: 'The Invisible Man Leadership Program'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    5ee7c67e-32cf-4b9c-b3fe-a14f86f2f60c: Title # Title
    6b6afd05-9cc6-4a8b-a9b0-426ae2ec21c5: 'Stats Table' # Stats Table
    7dd82277-b22c-4d92-993d-429ae8f92bf8: Common # Common
    8fea7832-8658-4760-82a2-fea191ae7ac0: Blocks # Blocks
    16c32343-c234-4479-a53b-8de7cad7cf71: 'The Invisible Man Leadership Program' # The Invisible Man Leadership Program
    67ed6635-8436-4a01-b83a-782899c82e34: foobar # foobar
    89c63208-2f9e-4fb3-9562-c5c4a709733f: Title # Title
    598a041c-a952-43d7-8130-a659fcddd233: Stats # Stats
    665f6825-9a80-4138-a2bf-847c424ec67b: 'Stat Item' # Stat Item
    1467d9bb-2f87-4770-aa6e-91b0edc0353b: 'The Invisible Man Leadership Program' # The Invisible Man Leadership Program
    5335c937-f52e-46bc-b450-ce1c783b5042: Title # Title
    7593fe81-7596-4faa-bef4-aac9d25d34e2: Hero # Hero
    b7cfb2f9-efc2-4e6f-b8a8-3d28d9d92e2f: Home # Home
    c9ad660a-b24e-4c3d-b87f-685185cc32f2: 'Background Image' # Background Image
    d5a81be2-83ca-46a2-a9d4-d97d68b8da6f: Home # Home
    f2206ae6-9a42-4b03-b6fd-c88253dff38c: 'Example Input' # Example Input
plugins:
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'The Invisible Man Leadership Program'
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
