defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  1467d9bb-2f87-4770-aa6e-91b0edc0353b: # The Invisible Man Leadership Program
    enabledByDefault: true
    hasUrls: true
    template: _pages/home.twig
    uriFormat: __home__
type: single
